[[schedule]]
owner = "Балакшин Павел Валерьевич"
date = "Четверг, 22 октября 2025 года"
week_type = "Even"

[[schedule.pair]]
[[schedule.pair.time]]
start_time = 17
end_time = 18

[[schedule.pair.info]]
group = "ИНФОРМ (P3116) 1.11"
place = "ул. Ломоносова д.9, лит.Е"
class = "1260/0 (Актовый зал)"
type = "Лабораторная"
format = "Очно-дистанционный"

[[schedule.pair]]
[[schedule.pair.time]]
start_time = "18:50"
end_time = "20:20"

[[schedule.pair.info]]
group = "ИНФОРМ (P3116) 1.11"
place = "ул. Ломоносова д.9, лит.Е"
class = "1260/0 (Актовый зал)"
type = "Лабораторная"
format = "Очно-дистанционный"
