window.main=Aðalgluggi
window.auth=Auðkenning
window.studyGroup=Námshópur

tab.main=Aðal
tab.visualization=Sjónræn framsetning

label.user=Notandi:
label.language=Tungumál
label.login=Innskráning
label.password=Lykilorð
label.filter=Sía:
label.sort=Röðun
label.command=Skipun
label.groupAdmin=Hópstjóri
label.hasGroupAdmin=Hefur hópstjóra
label.coordinates=Hnit
label.groupParams=Stillingar hóps

field.name=Nafn
field.x=X
field.y=Y
field.studentsCount=Fjöldi nemenda
field.expelledStudents=Brottvísaðir nemendur
field.shouldBeExpelled=Á að brottvísa
field.formOfEducation=Námsform
field.adminName=Nafn hópstjóra
field.adminWeight=Þyngd hópstjóra
field.eyeColor=Augnlitur
field.hairColor=Hárlitur

button.add=Bæta við
button.edit=Breyta
button.remove=Eyða
button.buy=Kaupa
button.clear=Hreinsa
button.refresh=Endurhlaða
button.logout=Skrá út
button.apply=Nota
button.reset=Núllstilla
button.execute=Keyra
button.login=Skrá inn
button.register=Nýskrá
button.ok=OK
button.cancel=Hætta við

table.id=ID
table.name=Nafn
table.x=X
table.y=Y
table.creationDate=Stofndagsetning
table.studentsCount=Nemendur
table.expelledStudents=Brottvísaðir
table.shouldBeExpelled=Á að brottvísa
table.formOfEducation=Námsform
table.groupAdmin=Hópstjóri
table.owner=Eigandi
table.price=Verð

message.chooseEdit=Veldu hlut til að breyta
message.chooseDelete=Veldu hlut til að eyða
message.chooseBuy=Veldu hlut til að kaupa
message.commandArgRequired=Sláðu inn viðfang skipunar.
message.commandArgNumber=Viðfangið verður að vera tala.
message.scriptDone=Skriftan var keyrð.
message.validationError=Villa
validation.nameRequired=Sláðu inn nafn.
validation.xRequired=Sláðu inn x.
validation.xMin=X verður að vera > -23.
validation.yRequired=Sláðu inn y.
validation.yMax=Y verður að vera <= 316.
validation.studentsRequired=Sláðu inn fjölda nemenda.
validation.studentsPositive=Fjöldi nemenda verður að vera meiri en 0.
validation.expelledRequired=Sláðu inn fjölda brottvísaðra nemenda.
validation.expelledPositive=Fjöldi brottvísaðra nemenda verður að vera meiri en 0.
validation.shouldBeExpelledPositive=Fjöldi nemenda sem á að brottvísa verður að vera meiri en 0.
validation.adminNameRequired=Sláðu inn nafn hópstjóra.
validation.adminWeightRequired=Sláðu inn þyngd hópstjóra.
validation.adminWeightPositive=Þyngd hópstjóra verður að vera > 0.
validation.eyeColorRequired=Veldu augnlit hópstjóra.
validation.hairColorRequired=Veldu hárlit hópstjóra.
