window.main=Главное окно
window.auth=Авторизация
window.studyGroup=Учебная группа

tab.main=Главная
tab.visualization=Визуализация

label.user=Пользователь:
label.language=Язык
label.login=Логин
label.password=Пароль
label.filter=Фильтр:
label.sort=Сортировка
label.command=Команда
label.argument=Аргумент
label.groupAdmin=Староста
label.hasGroupAdmin=Есть староста
label.coordinates=Координаты
label.groupParams=Параметры группы

field.name=Имя
field.x=X
field.y=Y
field.studentsCount=Количество студентов
field.expelledStudents=Отчислено студентов
field.shouldBeExpelled=Должно быть отчислено
field.formOfEducation=Форма обучения
field.adminName=Имя старосты
field.adminWeight=Вес старосты
field.eyeColor=Цвет глаз
field.hairColor=Цвет волос

button.add=Добавить
button.edit=Редактировать
button.remove=Удалить
button.buy=Купить
button.clear=Очистить
button.refresh=Обновить
button.logout=Выход
button.apply=Применить
button.reset=Сбросить
button.execute=Выполнить
button.login=Войти
button.register=Регистрация
button.ok=OK
button.cancel=Отмена

table.id=ID
table.name=Имя
table.x=X
table.y=Y
table.creationDate=Дата создания
table.studentsCount=Студентов
table.expelledStudents=Отчислено
table.shouldBeExpelled=Должно быть отчислено
table.formOfEducation=Форма обучения
table.groupAdmin=Староста
table.owner=Владелец
table.price=Цена

message.chooseEdit=Выберите элемент для редактирования
message.chooseDelete=Выберите элемент для удаления
message.chooseBuy=Выберите элемент для покупки
message.commandArgRequired=Введите аргумент команды.
message.commandArgNumber=Аргумент должен быть числом.
message.scriptDone=Скрипт выполнен.
message.validationError=Ошибка
validation.nameRequired=Введите имя.
validation.xRequired=Введите x.
validation.xMin=X должен быть > -23.
validation.yRequired=Введите y.
validation.yMax=Y должен быть <= 316.
validation.studentsRequired=Введите кол-во студентов.
validation.studentsPositive=Кол-во студентов должно быть больше 0.
validation.expelledRequired=Введите кол-во отчисленных студентов.
validation.expelledPositive=Кол-во отчисленных студентов должно быть больше 0.
validation.shouldBeExpelledPositive=Кол-во студентов, которые должны быть отчислены, должно быть больше 0.
validation.adminNameRequired=Укажите имя старосты.
validation.adminWeightRequired=Введите вес старосты.
validation.adminWeightPositive=Вес старосты должен быть > 0.
validation.eyeColorRequired=Выберите цвет глаз старосты.
validation.hairColorRequired=Выберите цвет волос старосты.
