@startuml

left to right direction
!theme plain
skinparam ranksep 20
skinparam nodesep 90

class CITY {
- ID(PRIMARY) : serial
- IS_POPULAR : boolean (NULL)
- CREATED_BY(FOREIGN) (integer) : PERSON(ID)
- PAST_ID(FOREIGN) : PAST(ID)
}

class PAST {
- ID(PRIMARY) : serial
- IS_FABRICATED : boolean (NULL)
- FABRICATED_CAREFULLY : boolean (NULL)
}

class PERSON {
- ID(PRIMARY) : serial
- NAME : text
- CITY_ID(FOREIGN) : CITY(ID)
}

CITY ---> PERSON : CREATED_BY:ID
CITY --> PAST : PAST_ID:ID
PERSON --> CITY : CITY_ID:ID
@enduml